sender:
  ip: "127.0.0.1"
  port: 5000

reflector:
  ip: "0.0.0.0"
  port: 50051


grpc:
  port: "50051"


server1:
  main: "localhost:50051"

network:
  server_address: "127.0.0.1"
  server_port: 9090
    # Tu as défini sender_port dans struct, ajoute-le ici
    # Même chose pour receiver_port
  listen_port: 5000
  packet_size: 1500
  timeout: "30s"

default_test:
  duration: "30s"
  interval: "1s"
  target_ip: "127.0.0.1"
  target_port: 5000

kafka:
  brokers:
    - "127.0.0.1:9092"
  test_request_topic: "test-requests"
  test_result_topic: "test-results"
  group_id: "test-group"

websocket:
  url: "ws://localhost:8082/ws"
